kind: deploymentPlan
namespace: production
active: production

database:
  liquibaseChangeLogs:
    - v1.0.0
    - v1.1.0
  url: jdbc:postgresql://wordsmith-production.ca3tifbqfpuf.us-east-1.rds.amazonaws.com:5432/wordsmith
  credentials: 
      jenkinsCredentialsId: postgresql-admin.production
applications:
  - release: wordsmith-api-production
    chart: wordsmith/wordsmith-api
    version: 1.0.10
    probe: https://api.production.wordsmith.beescloud.com/actuator/health
    values: wordsmith-api/values.yaml
    credentials:
      - jenkinsCredentialsId: postgresql.production
        helmUsernameParameter: database.username
        helmPasswordParameter: database.password
  - release: wordsmith-front-production
    chart: wordsmith/wordsmith-front
    version: "20180912.0857"
    probe: https://front.production.wordsmith.beescloud.com/
    values: wordsmith-front/values.yaml
  - release: www-production-canary
    chart: wordsmith/wordsmith-front
    version: "20180912.0859"
    probe: https://front-canary.production.wordsmith.beescloud.com/
    values: wordsmith-front/values-canary.yaml
